spring:
  config:
    activate:
      on-profile: aws
  cloud:
    aws:
      credentials:
        instance-profile: true    # usa el rol IAM del EC2/ECS
      region:
        static: ${AWS_REGION:us-east-1}

# En AWS real NO se usa endpoint override (se borra el default de LocalStack)
aws:
  endpoint: ""

entrypoint:
  sqs:
    endpoint: ""
