# application-local.yml — Ticket Service
spring:
  config:
    activate:
      on-profile: local

r2dbc:
  host: localhost
  database: esport_database
  username: admin
  password: password

aws:
  sqs:
    ticket-queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/ticket-update-queue
  endpoint: http://localhost:4566
  credentials:
    access-key: test
    secret-key: test
  region:
    static: us-east-1

entrypoint:
  sqs:
    region: us-east-1
    endpoint: http://localhost:4566
    queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/ticket-update-queue
    wait-time-seconds: 20
    visibility-timeout-seconds: 30
    max-number-of-messages: 10
    number-of-threads: 2

spring.data.redis:
  host: redis
  password: redis_pass

app:
  async:
    rabbit-mq:
      host: localhost
      port: 5672
      username: esport
      password: esport_pass
      virtual-host: /
