spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1

# LocalStack: se sobrescriben los endpoints para apuntar al contenedor local
aws:
  endpoint: ${AWS_ENDPOINT_OVERRIDE:http://localhost:4566}

entrypoint:
  sqs:
    endpoint: ${AWS_ENDPOINT_OVERRIDE:http://localhost:4566}
    queue-url: ${AWS_SQS_TICKET_URL:http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/ticket-update-queue}
    startup-delay-seconds: 5    # tiempo corto en local; no hay cold-start de ECS
