server:
  port: 8080
spring:
  application:
    name: "TournamentService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    host: localhost
    port: 5672
    username: esport
    password: esport123!
    ssl:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
r2dbc:
  host: localhost
  port: 5432
  database: esport_database
  username: admin
  password: password
logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
app:
  async:
    direct-async-gateway:
      enabled: true